from typing import Protocol, List, Dict, Any

class IMarketDataProvider(Protocol):
    async def fetch_data(self) -> List[Dict[str, Any]]: ...
    def get_cache_key(self) -> str: ...
    def get_asset_type(self) -> str: ...