from typing import Protocol, Optional
from ..auth.entities.user import User as DomainUser

class IUserRepository(Protocol):
    def get_by_id(self, user_id: int) -> Optional[DomainUser]: ...
    def get_by_email(self, email: str) -> Optional[DomainUser]: ...
    def email_exists(self, email: str) -> bool: ...
    def create(self, email: str, password: str, full_name: str) -> DomainUser: ...
    def verify_credentials(self, email: str, password: str) -> Optional[DomainUser]: ...